### ISSUE TITLE
Safari/ Push notification prompting can only be done from a user gesture.

### ISSUE THREAD

**Issue by ako-deriv** [Pushwoosh/web-push-notifications#30]
Our safari users keep getting this error!
![image](https://user-images.githubusercontent.com/81898967/141965984-3a6400a9-29ae-48bc-ae33-becd7389c981.png)
Screenshot has been taken from TrackJS
Is there any solution to solve this error?

**Comment by wfhm** [comment]
@ali-hosseini-fs,

Due to the [Safari 12.1 update made by Apple](https://developer.apple.com/documentation/safari-release-notes/safari-12_1-release-notes), an auto subscription upon SDK initialization is no longer available for Safari users.

In case you are wondering, all that a user gesture is in this case is something like a mouse click or page scroll. Essentially, Safari wants to ensure that a user is engaging with your website in some way before deploying any permission prompts.

The solution to this problem is to wait for a user gesture (e.g. a click on a button) and then display the permission prompt from that event. Use the `Pushwoosh.subscribe()` method that allows you to subscribe users under any button on the site or according to your site logic (ex. the user clicked on another page on your site and the method will be called).

You will find more details in our Guide: https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/web-push-notifications/web-push-sdk-3.0#public-methods

Another alternative, if you want to display the default Pushwoosh prompt as soon as the users land on your website, is to use a double opt-in for notifications. In this way, the permission prompt is still triggered from a user-generated event and you can also give useful information to the user in the first prompt.

You may find more specific information on this matter in the following article: https://docs.pushwoosh.com/platform-docs/v/v.2/manage-projects/subscription-prompt

**Comment by ako-deriv** [comment]
Thanks for your agile answer,
I just added an eventlistener on whole document to initialize the wooshpush after first click/tap.
